# Arise Application Challenge
---

Please answer the questions shown below by completing the code within this notebook and filling in your final answers in the respective block of the arise Challenge Answers form.

---

### Step 1 (this step does not have an answer in the answer form)

Please import the Pandas package. You will need to install the package if you do not already have them (`hint - google anaconda install pandas`).

In [1]:
# Add your code for Question 1 in this code block

---

### Step 2 (this step does not have an answer in the answer form)

Use Pandas to read in the csv titled `application_data.csv` as a Panda's dataframe. Once you have read in the data as a dataframe use Panda's `head()` function to show an overview of the data.

In [2]:
# Add your code for Question 2 in this code block

In [3]:
import pandas as pd

In [4]:
application = pd.read_csv("C:\Users\ChiefCollins\Arise-Applicants\Application_data.csv")

print(application)

    customerID        loanId appilcationDate  LoanNumber  LoanAmount  \
0    839247458  302953235622      2018-12-21           1      7500.0
1    217540860  302960101337      2018-12-23           1      7500.0
2    522238092  303016988846      2019-01-08           1      7500.0
3    096754469  302999605504      2019-01-04           1      7500.0
4    410354345  302951945878      2018-12-21           1      7500.0
5    027610141  302955854172      2018-12-22           6     45000.0
6    390748423  302941689535      2018-12-19           4     90000.0
7    642947351  302945727970      2018-12-19           3     45000.0
8    227382168  302953081988      2018-12-21           4     45000.0
9    380684555  302997991362      2019-01-03           4     30000.0
10   538656471  302906015723      2018-12-10           1     13500.0
11   067501201  302955909012      2018-12-22           4     19000.0
12   779403451  302941503245      2018-12-19           4     59500.0
13   706745423  302942096687      2018-12-19           1     32000.0
14   175032099  302948765318      2018-12-20           1      8000.0
15   756846529  302943137882      2018-12-19           7     16000.0
16   910833430  302985391002      2018-12-31           1     40500.0
17   789366247  302966696659      2018-12-25           7      9500.0
18   946771596  302919159103      2018-12-12           1     11000.0
19   363467351  302977645174      2018-12-28           1     11000.0
20   380721416  302935257840      2018-12-17           2     11000.0
21   476331961  302987067485      2018-12-31           1     11000.0
22   098589528  302933833928      2018-12-16           1     11000.0
23   063431769  302918179987      2018-12-12           1     11000.0
24   021449557  302982821720      2018-12-30           1     11000.0
25   826509061  302945064516      2018-12-19           1     11000.0
26   153423083  303028288661      2019-01-10           1     11000.0
27   369040052  302980904801      2018-12-29           1     11000.0
28   301885486  302990564127      2019-01-01           2     11000.0
29   134429368  302929098418      2018-12-15           1     11000.0
..         ...           ...             ...         ...         ...
970  012739639  301845465315      2018-06-03           5      7500.0
971  112612912     302707674      2018-01-29           3      7500.0
972  570857620     302918637      2018-03-14           2      7500.0
973  237077059  302447948799      2018-09-23           2      7500.0
974  981768947  301943354289      2018-06-22           2      7500.0
975  950533500     302651153      2018-01-18           2      7500.0
976  391025217     302607817      2018-01-08           1      7500.0
977  712496621  302515996811      2018-10-04           1      7500.0
978  189301655  302565959911      2018-10-13           2      7500.0
979  774788130     303200438      2018-05-09           6      7500.0
980  874756930     302885631      2018-03-07           2      7500.0
981  706415844  302867467601      2018-12-03           7      7500.0
982  620183677     302591220      2018-01-04           2      7500.0
983  351491824     302607848      2018-01-08           1      7500.0
984  913548727     302710986      2018-01-30           1      7500.0
985  238919660     302923409      2018-03-14           3      7500.0
986  671136860  302826707789      2018-11-26           2      7500.0
987  576830620     302856088      2018-03-01           3      7500.0
988  764722086     302931308      2018-03-16           2      7500.0
989  586613101     302585527      2018-01-03           3      7500.0
990  242227643  301880401914      2018-06-10           2      7500.0
991  078093608  302729421934      2018-11-09           2      7500.0
992  063243799     302605265      2018-01-08           2      7500.0
993  704294322     302631540      2018-01-14           1      7500.0
994  144227648     302582780      2018-01-02           2      7500.0
995  964510149     302636726      2018-01-15           2      7500.0
996  251997198     302772445      2018-02-13           1      7500.0
997  899011279     302585439      2018-01-03           3      7500.0
998  648637210  302788322114      2018-11-19           1      7500.0
999  464788691     302683579      2018-01-24           1      7500.0

     InterestRate  TermDays repaymentDueDate repaymentPaidDate
0            30.0        30       2019-01-20        2019-01-16
1            30.0        30       2019-01-22        2018-12-29
2            30.0        30       2019-02-07        2019-01-08
3            30.0        30       2019-02-03        2019-01-08
4            30.0        30       2019-01-20        2019-01-17
5            10.0        90       2019-03-21        2019-01-09
6             5.0       180       2019-06-18        2019-01-15
7            10.0        90       2019-03-19        2019-01-16
8            10.0        90       2019-03-20        2019-01-16
9            10.0        90       2019-04-02        2019-01-11
10           18.0        45       2019-01-24        2019-01-07
11           15.0        60       2019-02-21        2019-01-14
12            7.5       180       2019-06-18        2019-01-16
13            7.5       180       2019-06-18        2019-01-04
14           36.0        45       2019-02-03        2018-12-23
15           20.0        60       2019-02-18        2018-12-21
16           12.0       120       2019-04-30        2019-01-04
17           20.0        30       2019-01-24        2018-12-30
18           27.0        45       2019-01-26        2018-12-15
19           27.0        45       2019-02-11        2019-01-08
20           27.0        45       2019-01-31        2019-01-06
21           27.0        45       2019-02-14        2019-01-10
22           27.0        45       2019-01-31        2018-12-19
23           27.0        45       2019-01-26        2018-12-28
24           27.0        45       2019-02-13        2019-01-07
25           27.0        45       2019-02-02        2019-01-09
26           27.0        45       2019-02-24        2019-01-10
27           27.0        45       2019-02-12        2019-01-10
28           27.0        45       2019-02-15        2019-01-04
29           27.0        45       2019-01-29        2019-01-03
..            ...       ...              ...               ...
970          30.0        30       2018-07-03        2018-07-02
971          30.0        30       2018-02-28        2018-02-10
972          30.0        30       2018-04-13        2018-04-13
973          30.0        30       2018-10-23        2018-10-23
974          30.0        30       2018-07-23        2018-07-07
975          30.0        30       2018-02-17        2018-02-17
976          30.0        30       2018-02-08        2018-02-09
977          30.0        30       2018-11-03        2018-10-17
978          30.0        30       2018-11-12        2018-11-20
979          30.0        30       2018-06-08        2018-05-30
980          30.0        30       2018-04-06        2018-04-17
981          30.0        30       2019-01-02        2018-12-30
982          30.0        30       2018-02-03        2018-02-03
983          30.0        30       2018-02-09        2018-05-09
984          30.0        30       2018-03-01        2018-02-19
985          30.0        30       2018-04-14        2018-04-13
986          30.0        30       2018-12-27        2018-12-19
987          30.0        30       2018-03-31        2018-07-12
988          30.0        30       2018-04-15        2018-04-10
989          30.0        30       2018-02-02        2018-02-04
990          30.0        30       2018-07-10        2018-07-12
991          30.0        30       2018-12-09        2018-11-30
992          30.0        30       2018-02-07        2018-02-06
993          30.0        30       2018-02-13        2018-02-05
994          30.0        30       2018-02-01        2018-02-02
995          30.0        30       2018-02-14        2018-01-20
996          30.0        30       2018-03-15        2018-03-14
997          30.0        30       2018-02-02        2018-10-12
998          30.0        30       2018-12-19        2018-12-17
999          30.0        30       2018-02-24        2018-02-11

[1000 rows x 9 columns]

In [5]:
app_top = application.head()

print(app_top)

  customerID        loanId appilcationDate  LoanNumber  LoanAmount  \
0  839247458  302953235622      2018-12-21           1      7500.0
1  217540860  302960101337      2018-12-23           1      7500.0
2  522238092  303016988846      2019-01-08           1      7500.0
3  096754469  302999605504      2019-01-04           1      7500.0
4  410354345  302951945878      2018-12-21           1      7500.0

   InterestRate  TermDays repaymentDueDate repaymentPaidDate
0          30.0        30       2019-01-20        2019-01-16
1          30.0        30       2019-01-22        2018-12-29
2          30.0        30       2019-02-07        2019-01-08
3          30.0        30       2019-02-03        2019-01-08
4          30.0        30       2019-01-20        2019-01-17

You should now be able to see that the dataset contains information relating to loans that have been disbursed. Each row of the data is specific to a particular loan and displays the customer's ID that took out the loan, a unique loan ID, the date when the client applied for the loan, the loan number of the specific loan (how many loans the client has now taken out), the amount, interest rate, term days, the date when the loan repayment was due and the date the loan was actually repaid.

---

### Question 1

Convert `appilcationDate`, `repaymentDueDate` and `repaymentPaidDate` in the dataframes to datetimes.

In [6]:
# convert to dates
from datetime import datetime

In [7]:
application["appilcationDate"] = pd.to_datetime(application["appilcationDate"], format= "%Y-%m-%d")
application["repaymentDueDate"] = pd.to_datetime(application["repaymentDueDate"], format= "%Y-%m-%d")
application["repaymentPaidDate"] = pd.to_datetime(application["repaymentPaidDate"], format= "%Y-%m-%d")

print(application)

    customerID        loanId appilcationDate  LoanNumber  LoanAmount  \
0    839247458  302953235622      2018-12-21           1      7500.0
1    217540860  302960101337      2018-12-23           1      7500.0
2    522238092  303016988846      2019-01-08           1      7500.0
3    096754469  302999605504      2019-01-04           1      7500.0
4    410354345  302951945878      2018-12-21           1      7500.0
5    027610141  302955854172      2018-12-22           6     45000.0
6    390748423  302941689535      2018-12-19           4     90000.0
7    642947351  302945727970      2018-12-19           3     45000.0
8    227382168  302953081988      2018-12-21           4     45000.0
9    380684555  302997991362      2019-01-03           4     30000.0
10   538656471  302906015723      2018-12-10           1     13500.0
11   067501201  302955909012      2018-12-22           4     19000.0
12   779403451  302941503245      2018-12-19           4     59500.0
13   706745423  302942096687      2018-12-19           1     32000.0
14   175032099  302948765318      2018-12-20           1      8000.0
15   756846529  302943137882      2018-12-19           7     16000.0
16   910833430  302985391002      2018-12-31           1     40500.0
17   789366247  302966696659      2018-12-25           7      9500.0
18   946771596  302919159103      2018-12-12           1     11000.0
19   363467351  302977645174      2018-12-28           1     11000.0
20   380721416  302935257840      2018-12-17           2     11000.0
21   476331961  302987067485      2018-12-31           1     11000.0
22   098589528  302933833928      2018-12-16           1     11000.0
23   063431769  302918179987      2018-12-12           1     11000.0
24   021449557  302982821720      2018-12-30           1     11000.0
25   826509061  302945064516      2018-12-19           1     11000.0
26   153423083  303028288661      2019-01-10           1     11000.0
27   369040052  302980904801      2018-12-29           1     11000.0
28   301885486  302990564127      2019-01-01           2     11000.0
29   134429368  302929098418      2018-12-15           1     11000.0
..         ...           ...             ...         ...         ...
970  012739639  301845465315      2018-06-03           5      7500.0
971  112612912     302707674      2018-01-29           3      7500.0
972  570857620     302918637      2018-03-14           2      7500.0
973  237077059  302447948799      2018-09-23           2      7500.0
974  981768947  301943354289      2018-06-22           2      7500.0
975  950533500     302651153      2018-01-18           2      7500.0
976  391025217     302607817      2018-01-08           1      7500.0
977  712496621  302515996811      2018-10-04           1      7500.0
978  189301655  302565959911      2018-10-13           2      7500.0
979  774788130     303200438      2018-05-09           6      7500.0
980  874756930     302885631      2018-03-07           2      7500.0
981  706415844  302867467601      2018-12-03           7      7500.0
982  620183677     302591220      2018-01-04           2      7500.0
983  351491824     302607848      2018-01-08           1      7500.0
984  913548727     302710986      2018-01-30           1      7500.0
985  238919660     302923409      2018-03-14           3      7500.0
986  671136860  302826707789      2018-11-26           2      7500.0
987  576830620     302856088      2018-03-01           3      7500.0
988  764722086     302931308      2018-03-16           2      7500.0
989  586613101     302585527      2018-01-03           3      7500.0
990  242227643  301880401914      2018-06-10           2      7500.0
991  078093608  302729421934      2018-11-09           2      7500.0
992  063243799     302605265      2018-01-08           2      7500.0
993  704294322     302631540      2018-01-14           1      7500.0
994  144227648     302582780      2018-01-02           2      7500.0
995  964510149     302636726      2018-01-15           2      7500.0
996  251997198     302772445      2018-02-13           1      7500.0
997  899011279     302585439      2018-01-03           3      7500.0
998  648637210  302788322114      2018-11-19           1      7500.0
999  464788691     302683579      2018-01-24           1      7500.0

     InterestRate  TermDays repaymentDueDate repaymentPaidDate
0            30.0        30       2019-01-20        2019-01-16
1            30.0        30       2019-01-22        2018-12-29
2            30.0        30       2019-02-07        2019-01-08
3            30.0        30       2019-02-03        2019-01-08
4            30.0        30       2019-01-20        2019-01-17
5            10.0        90       2019-03-21        2019-01-09
6             5.0       180       2019-06-18        2019-01-15
7            10.0        90       2019-03-19        2019-01-16
8            10.0        90       2019-03-20        2019-01-16
9            10.0        90       2019-04-02        2019-01-11
10           18.0        45       2019-01-24        2019-01-07
11           15.0        60       2019-02-21        2019-01-14
12            7.5       180       2019-06-18        2019-01-16
13            7.5       180       2019-06-18        2019-01-04
14           36.0        45       2019-02-03        2018-12-23
15           20.0        60       2019-02-18        2018-12-21
16           12.0       120       2019-04-30        2019-01-04
17           20.0        30       2019-01-24        2018-12-30
18           27.0        45       2019-01-26        2018-12-15
19           27.0        45       2019-02-11        2019-01-08
20           27.0        45       2019-01-31        2019-01-06
21           27.0        45       2019-02-14        2019-01-10
22           27.0        45       2019-01-31        2018-12-19
23           27.0        45       2019-01-26        2018-12-28
24           27.0        45       2019-02-13        2019-01-07
25           27.0        45       2019-02-02        2019-01-09
26           27.0        45       2019-02-24        2019-01-10
27           27.0        45       2019-02-12        2019-01-10
28           27.0        45       2019-02-15        2019-01-04
29           27.0        45       2019-01-29        2019-01-03
..            ...       ...              ...               ...
970          30.0        30       2018-07-03        2018-07-02
971          30.0        30       2018-02-28        2018-02-10
972          30.0        30       2018-04-13        2018-04-13
973          30.0        30       2018-10-23        2018-10-23
974          30.0        30       2018-07-23        2018-07-07
975          30.0        30       2018-02-17        2018-02-17
976          30.0        30       2018-02-08        2018-02-09
977          30.0        30       2018-11-03        2018-10-17
978          30.0        30       2018-11-12        2018-11-20
979          30.0        30       2018-06-08        2018-05-30
980          30.0        30       2018-04-06        2018-04-17
981          30.0        30       2019-01-02        2018-12-30
982          30.0        30       2018-02-03        2018-02-03
983          30.0        30       2018-02-09        2018-05-09
984          30.0        30       2018-03-01        2018-02-19
985          30.0        30       2018-04-14        2018-04-13
986          30.0        30       2018-12-27        2018-12-19
987          30.0        30       2018-03-31        2018-07-12
988          30.0        30       2018-04-15        2018-04-10
989          30.0        30       2018-02-02        2018-02-04
990          30.0        30       2018-07-10        2018-07-12
991          30.0        30       2018-12-09        2018-11-30
992          30.0        30       2018-02-07        2018-02-06
993          30.0        30       2018-02-13        2018-02-05
994          30.0        30       2018-02-01        2018-02-02
995          30.0        30       2018-02-14        2018-01-20
996          30.0        30       2018-03-15        2018-03-14
997          30.0        30       2018-02-02        2018-10-12
998          30.0        30       2018-12-19        2018-12-17
999          30.0        30       2018-02-24        2018-02-11

[1000 rows x 9 columns]

Now that the dates have been converted, How many `unique`data types are contained within the application dataset?

In [8]:
# data types

print(application.dtypes)
print()
print(application.info())

customerID                   object
loanId                       object
appilcationDate      datetime64[ns]
LoanNumber                    int64
LoanAmount                  float64
InterestRate                float64
TermDays                      int64
repaymentDueDate     datetime64[ns]
repaymentPaidDate    datetime64[ns]
dtype: object
()
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 9 columns):
customerID           1000 non-null object
loanId               1000 non-null object
appilcationDate      1000 non-null datetime64[ns]
LoanNumber           1000 non-null int64
LoanAmount           1000 non-null float64
InterestRate         1000 non-null float64
TermDays             1000 non-null int64
repaymentDueDate     1000 non-null datetime64[ns]
repaymentPaidDate    1000 non-null datetime64[ns]
dtypes: datetime64[ns](3), float64(2), int64(2), object(2)
memory usage: 70.4+ KB
None

### Question 2

Please calculate the `average` loan amount, interest rate and termdays for all the loans in the dataset? `Round` all number to two decimal places.

In [9]:
# 2a avg loan amount
print(round(application["LoanAmount"].mean(),2))

13828.08

In [10]:
# 2b avg interest rate
print(round(application["InterestRate"].mean(),2))

23.06

In [11]:
# 2c avg term days 
print(round(application["TermDays"].mean(),2))

42.08

---

### Question 3

Please create a new column called `dateDifference` which needs to contains the number of days between when the loan was repaid and when it was due to be repaid. 

Count the number of loans that were paid more than 3 days late. This can be done by first creating a dataframe only containing the loans that were paid more than 3 days late.

In [13]:
# number of loans more than 3 days late

#We use the dt.days method to convert from timedelta to interger in order to perform the boolean comparison
application["dateDifference"] = (application["repaymentPaidDate"] - application["repaymentDueDate"]).dt.days

defaulters = application[application["dateDifference"]>3]

print(application)
print()
print()
print(defaulters)
print()
print("Loans paid after 3days of default is = ", defaulters.shape[0])

    customerID        loanId appilcationDate  LoanNumber  LoanAmount  \
0    839247458  302953235622      2018-12-21           1      7500.0
1    217540860  302960101337      2018-12-23           1      7500.0
2    522238092  303016988846      2019-01-08           1      7500.0
3    096754469  302999605504      2019-01-04           1      7500.0
4    410354345  302951945878      2018-12-21           1      7500.0
5    027610141  302955854172      2018-12-22           6     45000.0
6    390748423  302941689535      2018-12-19           4     90000.0
7    642947351  302945727970      2018-12-19           3     45000.0
8    227382168  302953081988      2018-12-21           4     45000.0
9    380684555  302997991362      2019-01-03           4     30000.0
10   538656471  302906015723      2018-12-10           1     13500.0
11   067501201  302955909012      2018-12-22           4     19000.0
12   779403451  302941503245      2018-12-19           4     59500.0
13   706745423  302942096687      2018-12-19           1     32000.0
14   175032099  302948765318      2018-12-20           1      8000.0
15   756846529  302943137882      2018-12-19           7     16000.0
16   910833430  302985391002      2018-12-31           1     40500.0
17   789366247  302966696659      2018-12-25           7      9500.0
18   946771596  302919159103      2018-12-12           1     11000.0
19   363467351  302977645174      2018-12-28           1     11000.0
20   380721416  302935257840      2018-12-17           2     11000.0
21   476331961  302987067485      2018-12-31           1     11000.0
22   098589528  302933833928      2018-12-16           1     11000.0
23   063431769  302918179987      2018-12-12           1     11000.0
24   021449557  302982821720      2018-12-30           1     11000.0
25   826509061  302945064516      2018-12-19           1     11000.0
26   153423083  303028288661      2019-01-10           1     11000.0
27   369040052  302980904801      2018-12-29           1     11000.0
28   301885486  302990564127      2019-01-01           2     11000.0
29   134429368  302929098418      2018-12-15           1     11000.0
..         ...           ...             ...         ...         ...
970  012739639  301845465315      2018-06-03           5      7500.0
971  112612912     302707674      2018-01-29           3      7500.0
972  570857620     302918637      2018-03-14           2      7500.0
973  237077059  302447948799      2018-09-23           2      7500.0
974  981768947  301943354289      2018-06-22           2      7500.0
975  950533500     302651153      2018-01-18           2      7500.0
976  391025217     302607817      2018-01-08           1      7500.0
977  712496621  302515996811      2018-10-04           1      7500.0
978  189301655  302565959911      2018-10-13           2      7500.0
979  774788130     303200438      2018-05-09           6      7500.0
980  874756930     302885631      2018-03-07           2      7500.0
981  706415844  302867467601      2018-12-03           7      7500.0
982  620183677     302591220      2018-01-04           2      7500.0
983  351491824     302607848      2018-01-08           1      7500.0
984  913548727     302710986      2018-01-30           1      7500.0
985  238919660     302923409      2018-03-14           3      7500.0
986  671136860  302826707789      2018-11-26           2      7500.0
987  576830620     302856088      2018-03-01           3      7500.0
988  764722086     302931308      2018-03-16           2      7500.0
989  586613101     302585527      2018-01-03           3      7500.0
990  242227643  301880401914      2018-06-10           2      7500.0
991  078093608  302729421934      2018-11-09           2      7500.0
992  063243799     302605265      2018-01-08           2      7500.0
993  704294322     302631540      2018-01-14           1      7500.0
994  144227648     302582780      2018-01-02           2      7500.0
995  964510149     302636726      2018-01-15           2      7500.0
996  251997198     302772445      2018-02-13           1      7500.0
997  899011279     302585439      2018-01-03           3      7500.0
998  648637210  302788322114      2018-11-19           1      7500.0
999  464788691     302683579      2018-01-24           1      7500.0

     InterestRate  TermDays repaymentDueDate repaymentPaidDate  dateDifference
0            30.0        30       2019-01-20        2019-01-16              -4
1            30.0        30       2019-01-22        2018-12-29             -24
2            30.0        30       2019-02-07        2019-01-08             -30
3            30.0        30       2019-02-03        2019-01-08             -26
4            30.0        30       2019-01-20        2019-01-17              -3
5            10.0        90       2019-03-21        2019-01-09             -71
6             5.0       180       2019-06-18        2019-01-15            -154
7            10.0        90       2019-03-19        2019-01-16             -62
8            10.0        90       2019-03-20        2019-01-16             -63
9            10.0        90       2019-04-02        2019-01-11             -81
10           18.0        45       2019-01-24        2019-01-07             -17
11           15.0        60       2019-02-21        2019-01-14             -38
12            7.5       180       2019-06-18        2019-01-16            -153
13            7.5       180       2019-06-18        2019-01-04            -165
14           36.0        45       2019-02-03        2018-12-23             -42
15           20.0        60       2019-02-18        2018-12-21             -59
16           12.0       120       2019-04-30        2019-01-04            -116
17           20.0        30       2019-01-24        2018-12-30             -25
18           27.0        45       2019-01-26        2018-12-15             -42
19           27.0        45       2019-02-11        2019-01-08             -34
20           27.0        45       2019-01-31        2019-01-06             -25
21           27.0        45       2019-02-14        2019-01-10             -35
22           27.0        45       2019-01-31        2018-12-19             -43
23           27.0        45       2019-01-26        2018-12-28             -29
24           27.0        45       2019-02-13        2019-01-07             -37
25           27.0        45       2019-02-02        2019-01-09             -24
26           27.0        45       2019-02-24        2019-01-10             -45
27           27.0        45       2019-02-12        2019-01-10             -33
28           27.0        45       2019-02-15        2019-01-04             -42
29           27.0        45       2019-01-29        2019-01-03             -26
..            ...       ...              ...               ...             ...
970          30.0        30       2018-07-03        2018-07-02              -1
971          30.0        30       2018-02-28        2018-02-10             -18
972          30.0        30       2018-04-13        2018-04-13               0
973          30.0        30       2018-10-23        2018-10-23               0
974          30.0        30       2018-07-23        2018-07-07             -16
975          30.0        30       2018-02-17        2018-02-17               0
976          30.0        30       2018-02-08        2018-02-09               1
977          30.0        30       2018-11-03        2018-10-17             -17
978          30.0        30       2018-11-12        2018-11-20               8
979          30.0        30       2018-06-08        2018-05-30              -9
980          30.0        30       2018-04-06        2018-04-17              11
981          30.0        30       2019-01-02        2018-12-30              -3
982          30.0        30       2018-02-03        2018-02-03               0
983          30.0        30       2018-02-09        2018-05-09              89
984          30.0        30       2018-03-01        2018-02-19             -10
985          30.0        30       2018-04-14        2018-04-13              -1
986          30.0        30       2018-12-27        2018-12-19              -8
987          30.0        30       2018-03-31        2018-07-12             103
988          30.0        30       2018-04-15        2018-04-10              -5
989          30.0        30       2018-02-02        2018-02-04               2
990          30.0        30       2018-07-10        2018-07-12               2
991          30.0        30       2018-12-09        2018-11-30              -9
992          30.0        30       2018-02-07        2018-02-06              -1
993          30.0        30       2018-02-13        2018-02-05              -8
994          30.0        30       2018-02-01        2018-02-02               1
995          30.0        30       2018-02-14        2018-01-20             -25
996          30.0        30       2018-03-15        2018-03-14              -1
997          30.0        30       2018-02-02        2018-10-12             252
998          30.0        30       2018-12-19        2018-12-17              -2
999          30.0        30       2018-02-24        2018-02-11             -13

[1000 rows x 10 columns]
()
()
     customerID        loanId appilcationDate  LoanNumber  LoanAmount  \
397  GH35460722     100016172      2018-01-30           5        80.0
410  GH85390929     100015715      2018-01-27           2        80.0
419  GH06832511     100014400      2018-01-20           1        80.0
424  GH26139148     100017099      2018-02-04           2        80.0
426  GH03825373     100012495      2018-01-13           1        80.0
432  GH63887800     100016727      2018-02-02           2        80.0
446  GH33164754     100014274      2018-01-19           5        80.0
448  GH28179321     100016682      2018-02-02           5        80.0
449  GH96880686     100012940      2018-01-14           1        80.0
450  GH80713260     100017839      2018-02-08           4        80.0
456  GH28179321     100011014      2018-01-06           4        80.0
457  GH59483030     100017217      2018-02-05           5        80.0
459  GH00205281     100016094      2018-01-29           2        80.0
462  GH96908526     100013425      2018-01-16           3        80.0
469  GH91278408     100017825      2018-02-08           2        80.0
474  GH63727524     100015090      2018-01-23           1        80.0
491  GH44856685     100016872      2018-02-02           5        80.0
517  GH67529775     100017455      2018-02-06           2        80.0
531   739546510  302060935730      2018-07-17           6     20500.0
532   051964302  302344421107      2018-09-06           4     20500.0
544   026133837     302623360      2018-01-12           2      7500.0
547   124189650     302607241      2018-01-08           1      7500.0
549   061452364  302528776595      2018-10-06           2      7500.0
551   383789899     302833086      2018-02-25           1      7500.0
553   339095931  302379245789      2018-09-12           2      7500.0
554   091351436     302832471      2018-02-25           1      7500.0
555   683225743  302072465932      2018-07-19           5      7500.0
557   530961303     302716663      2018-01-31           2      7500.0
560   974013962     302583090      2018-01-02           1      7500.0
562   751741585     303138149      2018-04-28           1      7500.0
..          ...           ...             ...         ...         ...
890   159945550  302589833904      2018-10-17           1      7500.0
891   032311940  301993996930      2018-07-03           2      7500.0
896   466262330     302846873      2018-02-27           2      7500.0
907   686558059  301982521136      2018-06-30           2      7500.0
908   912290005     302744019      2018-02-06           1      7500.0
912   657637051     302590779      2018-01-04           1      7500.0
914   191115740     302657503      2018-01-19           2      7500.0
917   151876969     302786072      2018-02-15           1      7500.0
919   251839715  302368523945      2018-09-10           1      7500.0
926   068296451     303008698      2018-04-03           2      7500.0
927   139420975     302863390      2018-03-02           1      7500.0
929   031947410  301822930431      2018-05-30           2      7500.0
932   749085876  301884588348      2018-06-11           4      7500.0
934   049163426     302779934      2018-02-14           1      7500.0
941   166319502  302303049493      2018-08-30           3      7500.0
947   826407015  302353101661      2018-09-07          12      7500.0
951   920806253  302471845612      2018-09-27           1      7500.0
952   729934026  301795211670      2018-05-24           1      7500.0
956   121586610  302178919277      2018-08-08           3      7500.0
960   482610334  302370502585      2018-09-10           1      7500.0
962   492954954     303201761      2018-05-09           1      7500.0
963   859200358     302701019      2018-01-28           3      7500.0
964   631264575     302600338      2018-01-06           1      7500.0
965   738664536     303004277      2018-04-01           1      7500.0
967   745141607  302227740886      2018-08-17           1      7500.0
978   189301655  302565959911      2018-10-13           2      7500.0
980   874756930     302885631      2018-03-07           2      7500.0
983   351491824     302607848      2018-01-08           1      7500.0
987   576830620     302856088      2018-03-01           3      7500.0
997   899011279     302585439      2018-01-03           3      7500.0

     InterestRate  TermDays repaymentDueDate repaymentPaidDate  dateDifference
397          15.0        15       2018-02-14        2018-03-01              15
410          15.0        15       2018-02-12        2018-02-16               4
419          15.0        15       2018-02-05        2018-02-14               9
424          15.0        15       2018-02-19        2018-02-27               8
426          15.0        15       2018-01-29        2018-02-13              15
432          15.0        15       2018-02-19        2018-02-25               6
446          15.0        15       2018-02-05        2018-02-12               7
448          15.0        15       2018-02-19        2018-02-28               9
449          15.0        15       2018-01-29        2018-02-17              19
450          15.0        15       2018-02-23        2018-02-27               4
456          15.0        15       2018-01-22        2018-01-31               9
457          15.0        15       2018-02-20        2018-04-04              43
459          15.0        15       2018-02-13        2018-02-27              14
462          15.0        15       2018-01-31        2018-02-19              19
469          15.0        15       2018-02-23        2018-03-29              34
474          15.0        15       2018-02-07        2018-05-28             110
491          15.0        15       2018-02-19        2018-03-05              14
517          15.0        15       2018-02-21        2018-03-05              12
531          20.0        60       2018-09-16        2018-12-22              97
532          20.0        60       2018-11-06        2018-12-01              25
544          30.0        30       2018-02-11        2018-03-24              41
547          30.0        30       2018-02-09        2018-03-30              49
549          30.0        30       2018-11-05        2018-11-14               9
551          30.0        30       2018-03-29        2018-04-12              14
553          30.0        30       2018-10-12        2018-10-31              19
554          30.0        30       2018-03-27        2018-04-24              28
555          30.0        30       2018-08-20        2018-09-25              36
557          30.0        30       2018-03-02        2018-03-07               5
560          30.0        30       2018-02-04        2018-03-06              30
562          30.0        30       2018-05-28        2018-07-28              61
..            ...       ...              ...               ...             ...
890          30.0        30       2018-11-16        2018-12-06              20
891          30.0        30       2018-08-02        2018-08-06               4
896          30.0        30       2018-03-29        2018-04-09              11
907          30.0        30       2018-07-30        2018-09-08              40
908          30.0        30       2018-03-08        2018-05-23              76
912          30.0        30       2018-02-03        2018-03-13              38
914          30.0        30       2018-02-18        2018-02-22               4
917          30.0        30       2018-03-17        2018-03-21               4
919          30.0        30       2018-10-10        2018-10-24              14
926          30.0        30       2018-05-03        2018-05-08               5
927          30.0        30       2018-04-01        2018-10-08             190
929          30.0        30       2018-06-29        2018-09-25              88
932          30.0        30       2018-07-11        2018-09-01              52
934          30.0        30       2018-03-16        2018-05-09              54
941          30.0        30       2018-09-29        2018-10-03               4
947          30.0        30       2018-10-07        2018-10-18              11
951          30.0        30       2018-10-27        2018-11-09              13
952          30.0        30       2018-06-25        2018-07-05              10
956          30.0        30       2018-09-07        2018-09-27              20
960          30.0        30       2018-10-10        2018-11-12              33
962          30.0        30       2018-06-08        2018-07-25              47
963          30.0        30       2018-02-27        2018-03-07               8
964          30.0        30       2018-02-05        2018-04-29              83
965          30.0        30       2018-05-03        2018-06-06              34
967          30.0        30       2018-09-16        2018-10-16              30
978          30.0        30       2018-11-12        2018-11-20               8
980          30.0        30       2018-04-06        2018-04-17              11
983          30.0        30       2018-02-09        2018-05-09              89
987          30.0        30       2018-03-31        2018-07-12             103
997          30.0        30       2018-02-02        2018-10-12             252

[145 rows x 10 columns]
()
('Loans paid after 3days of default is = ', 145)

---

### Question 4

Please group the dataset by `TermDays` and calculate the `mean` loan amount and the `standard deviation` of loan amount within each term.

What is the mean loan amount in 30-day loans and what is the standard deviation of  loan amount in 90-day loans? Please give your answers to the nearest two decimal places.

In [18]:
# mean loan amount in 30-day loans and standard deviation of loan amount in 90-day loans
group_termDays = application.groupby("TermDays").count()

print(group_termDays)

          customerID  loanId  appilcationDate  LoanNumber  LoanAmount  \
TermDays
15               159     159              159         159         159
30               560     560              560         560         560
45                80      80               80          80          80
60                95      95               95          95          95
90                55      55               55          55          55
120                9       9                9           9           9
180               42      42               42          42          42

          InterestRate  repaymentDueDate  repaymentPaidDate  dateDifference
TermDays
15                 159               159                159             159
30                 560               560                560             560
45                  80                80                 80              80
60                  95                95                 95              95
90                  55                55                 55              55
120                  9                 9                  9               9
180                 42                42                 42              42

In [19]:
mean_termDays = application.groupby("TermDays")[["LoanAmount"]].mean().round(2)

std_termDays = application.groupby("TermDays")[["LoanAmount"]].std().round(2)



print(mean_termDays)
print()
print(std_termDays)
print()

          LoanAmount
TermDays
15           1274.09
30           7941.96
45          10706.25
60          25710.53
90          37672.73
120         45055.56
180         80988.10
()
          LoanAmount
TermDays
15           2885.97
30           1606.04
45           2346.14
60          11559.65
90          18050.14
120         22192.97
180         34612.22
()

---

### Question 5

`Late` loans are defined as loans that were paid `more than 3 days` after their due date. Please find the average number of days that these loans were paid beyond their due date for each `week of the year`. This will require you to break all `appilcationDate's` down into the week of the year they were made and then perform a group by. 

What is the average number of days that `late` loans applied for in the second week of the year were paid late? Please sumbit your answer rounded to two decimal places.

In [21]:
# week of year and average number of late days

defaulters["Wk_no"] = defaulters["appilcationDate"].dt.week

defaulters_grp = defaulters.groupby("Wk_no")[["dateDifference"]].mean().round(2)

print(defaulters_grp)

       dateDifference
Wk_no
1               87.60
2               45.75
3               16.50
4               37.92
5               18.00
6               39.71
7               29.25
8               25.15
9               55.86
10              29.25
11              71.50
12              19.50
13              34.00
14              14.00
15               7.00
17              34.50
19              66.50
20              28.00
21              10.00
22              88.00
23              11.00
24              36.00
26              27.33
27               4.00
28               7.00
29              69.00
30              65.00
31             108.00
32              15.50
33              30.00
34              14.00
35               4.00
36              39.33
37              17.20
38              60.00
39               9.00
40               9.00
41               8.00
42              20.00
44               9.00
45               6.00
48              18.00

C:\Users\ChiefCollins\Anaconda2\lib\site-packages\ipykernel_launcher.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  This is separate from the ipykernel package so we can avoid doing imports until

---

### The End

Thank you for completing the challenge. Please make sure you have submitted all of your answers to the arise Challenge Answers form.

### Notebook
Please save you notebook as `yourEmail.ipynb` where you replace `yourEmail` with your actual email address and attach it to the arise Challenge Answers form.